#ifndef EMPLEADOS_H_INCLUDED
#define EMPLEADOS_H_INCLUDED
//PRE:
//POST:SE CREA LA STRUCT CON SUS TIPOS DE DATOS
struct EmpleadoE;
//PRE:LA STRUCT FUE CREADA
//POST:SE CREA UN TIPO DE DATO STRUCT Y EL PUNTERO QUE APUNTA AL MISMO
typedef struct EmpleadoE * Empleado;
//PRE: EL TIPO DE DATO STRUCT FUE DEFINIDO. TAMBIÉN EL PUNTERO Empleado ASOCIADO A LA STRUCT
//POST: SE CREA POR PARAMETRO AL EMPLEADO. LOS PARAMETROS SON LOS DATOS DEL EMPLEADO
Empleado crearEmpleado(char nom[], char ape[], int ed);
//PRE: SE CARGO AL EMPLEADO POR crearEmpleado...
//POST: SE MUESTRA POR PANTALLA A LOS EMPLEADOS
void mostrarEmpleado(Empleado e);
//PRE:LA STRUCT DEBE ESTAR CREADA CON LOS DATOS CORRESPONDIENTES
//POST:INICIA LA CARGA DE EMPLEADOS SIN BASURA
int iniciarCargaEmpleados();
//PRE:LOS DATOS DE LA STRUCT HAN SIDO CARGADOS
//POST:ORDENA LOS EMPLEADOS POR SUELDO Y SE PASA LA FUNCIÓN A empresa.c PARA MOSTRARLOS POR PANTALLA
void ordenamientoSeleccion(Empleado e[]);
int getEdad(Empleado e);






#endif // EMPLEADOS_H_INCLUDED
